# Generated by Django 2.0.7 on 2019-05-24 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desc',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='api.ProjectType', verbose_name='项目类别'),
        ),
    ]
