# Generated by Django 2.0.7 on 2019-07-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190525_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dbname',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='表名称'),
        ),
    ]
