# Generated by Django 2.0.7 on 2019-05-14 06:41

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projecttype',
            table=None,
        ),
    ]
